language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python:
        - "2.7"
        - "3.4"
        - "3.5"
        - "3.6"      # current default Python on Travis CI
        - "3.7"
        - "3.8"
        - "3.8-dev"  # 3.8 development branch
        - "nightly"  # nightly build
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
# command to install dependencies
install:
  #- pip install -r requirements.txt
  - conda install -c conda-forge numpy
  - conda install -c conda-forge affine
  - conda install -c conda-forge fiona
  - conda install -c conda-forge proj
  - conda install -c conda-forge pyproj
  - conda install -c conda-forge gdal
  - conda install -c conda-forge pandas
  - conda install -c conda-forge geopandas
  - conda install -c conda-forge matplotlib
  - conda install -c conda-forge python
  - conda install -c conda-forge scipy
  - conda install -c conda-forge shapely
  - conda install -c conda-forge statsmodels
  - conda install -c conda-forge rasterio
  - python setup.py install
# command to run tests
script:
  - python Examples/test.py