language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
env: DEPS= "numpy affine fiona proj pyproj gdal pandas geopandas matplotlib python scipy shapely statsmodels rasterio"
before_install:
  # Install the latest version of Miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - conda info -a
# command to install dependencies
install:
  # Create a new environment
  - conda create -q -n Hapi-env python=${TRAVIS_PYTHON_VERSION} --yes
  - source activate Hapi-env
  # Install various dependencies
  - conda install --yes $DEPS pip

  # You can add any CONDA channels you may need here. CONDA supports
  # both the commands add and append. The only difference is that 
  # the add command places the channel at the front of the priority 
  # list, while append does the opposite.
  - conda config --add channels conda-forge

  - python -V
  - python setup.py build_ext --inplace
  - python setup.py install
  - cd ..
# command to run tests
script:
  - python Examples/test.py