channels:
  - conda-forge
  - udst
  - https://conda.anaconda.org/mutirri
  - defaults
dependencies:
  - pip=20.0.2
  - numpy
  - fiona
  - gdal
  - geopandas
  - geos=3.8.1
  - matplotlib
  - pandas
  - proj
  - pyproj
  - python
  - scipy
  - setuptools
  - shapely
  - statsmodels
  - pip:
    - hapi-nile==0.1.0

