channels:
  - conda-forge
  - udst
  - https://conda.anaconda.org/mutirri
  - defaults
dependencies:
  - pip
  - numpy
  - affine
  #- snuggs=1.4.7
  #- click-plugins=1.1.1
  #- conda=4.8.*
  #- fiona=1.8.*
  - proj
  - pyproj
  - gdal
  - pandas
  - geopandas
  - geos
  - matplotlib
  - python
  - scipy
  - setuptools
  - shapely
  - statsmodels
  - rasterio
  - pip:
    #- hapi-nile==0.1.0
    - git+https://github.com/MAfarrag/HAPI.git
