channels:
  - conda-forge
  - mafarrag
dependencies:
  - pip
  - numpy
  - affine
  - fiona
  - proj
  - pyproj
  - gdal
  - pandas
  - geopandas
  - matplotlib
  - python
  - scipy
  - shapely
  - statsmodels
  - rasterio
  - rasterstats
  - oasis
  - pip:
    #- hapi-nile==0.1.0
    - git+https://github.com/MAfarrag/HAPI.git
