site_name: Hapi
#site_url: 
site_description: The documentation of Hapi Hydrological Model
site_author: Mostafa Farrag

repo_url: https://github.com/MAfarrag/Hapi
edit_url: ""

theme:
    name: readthedocs

nav:
    - Home: Introduction.md
    - Content: index.md
    - Tutorial:
        - Getting Started: getting_started.md
        - Inputs: Inputs.md
        - Lumped Hydrological Model: Lumped_HBV.md
        - Hydrological model: Hydrological_model.md
        - Sensitivity Analysis: Sensitivity_Analysis.md

    - About:
        - License: license.md



