{% set version = "0.1.0" %}

package:
  name: hapi
  version: {{ version }}

source:
  path: F:\01Algorithms\HAPI

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
  - pip
  - numpy
  - affine
  - fiona
  - proj
  - pyproj
  - gdal
  - pandas
  - geopandas
  - matplotlib
  - python
  - scipy
  - shapely
  - statsmodels
  - rasterio
  run:
    - pip
    - numpy
    - affine
    - fiona
    - proj
    - pyproj
    - gdal
    - pandas
    - geopandas
    - matplotlib
    - python
    - scipy
    - shapely
    - statsmodels
    - rasterio

test:
  imports:
    - Hapi

about:
  home: https://github.com/MAfarrag/HAPI
  license: MIT
  summary: 'Distributed Hydrological model'
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/MAfarrag/HAPI
  doc_url: https://github.com/MAfarrag/HAPI
  doc_source_url: https://github.com/MAfarrag/HAPI/master/README.md