{% set version = "1.0.0" %}

package:
  name: hapi
  version: {{ version }}

source:
  path: F:\01Algorithms\Hydrology\HAPI

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

channels:
  - mafarrag
  - conda-forge  

requirements:
  host:
  - pip
  - numpy
  - affine
  - fiona
  - proj
  - pyproj
  - gdal
  - pandas
  - geopandas
  - matplotlib
  - python
  - scipy
  - shapely
  - statsmodels
  - rasterio
  - rasterstats
  - oasis
  - netCDF4
  - scikit-learn
  - scikit-image
  - ecmwf-api-client
  run:
    - pip
    - numpy
    - affine
    - fiona
    - proj
    - pyproj
    - gdal
    - pandas
    - geopandas
    - matplotlib
    - python
    - scipy
    - shapely
    - statsmodels
    - rasterio
    - rasterstats
    - oasis
    - netCDF4
    - scikit-learn
    - scikit-image
    - ecmwf-api-client

test:
  imports:
    - Hapi

about:
  home: https://github.com/MAfarrag/HAPI
  license: MIT
  summary: 'Distributed Hydrological model'
  description: |
    This module builds Distributed Hydrological model.
  dev_url: https://github.com/MAfarrag/HAPI
  doc_url: https://github.com/MAfarrag/HAPI
  doc_source_url: https://github.com/MAfarrag/HAPI/master/README.md