{% set version = "0.1.0" %}

package:
  name: hapi
  version: {{ version }}

source:
  path: F:\01Algorithms\anaconda-package\HAPI

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - numpy==1.18.*
    - affine=2.3.*
    - fiona=1.8.*
    - proj=6.3.*
    - pyproj=2.6.*  
    - gdal=3.0.*
    - pandas=1.0.*
    - geopandas=0.7.*
    - geos=3.8.*
    - matplotlib=3.2.*
    - matplotlib-base=3.2.*
    - python=3.7.*
    - scipy=1.3.*
    - setuptools
    - shapely=1.7.*
    - statsmodels=0.11.*
    - rasterio=1.1.*
  run:
    - python
    - pip
    - numpy==1.18.*
    - affine=2.3.*
    - fiona=1.8.*
    - proj=6.3.*
    - pyproj=2.6.*  
    - gdal=3.0.*
    - pandas=1.0.*
    - geopandas=0.7.*
    - geos=3.8.*
    - matplotlib=3.2.*
    - matplotlib-base=3.2.*
    - python=3.7.*
    - scipy=1.3.*
    - setuptools
    - shapely=1.7.*
    - statsmodels=0.11.*
    - rasterio=1.1.*

test:
  imports:
    - HAPI

about:
  home: https://github.com/shibukawa/imagesize_py
  license: MIT
  summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/shibukawa/imagesize_py
  doc_url: https://pypi.python.org/pypi/imagesize
  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst